---
booktitle: Proceedings of The KDD'21 Workshop on Causal Discovery
shortname: CD2021
volume: '150'
year: '2021'
start: 2021-08-15
end: 2021-08-15
published: 2021-08-02
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CD2021
month: 0
cycles: false
bibtex_editor: Le, Thuc Duy and Li, Jiuyong and Cooper, Greg and Triantafyllou, Sofia
  and Bareinboim, Elias and Liu, Huan and Kiyavash, Negar
editor:
- given: Thuc Duy
  family: Le
- given: Jiuyong
  family: Li
- given: Greg
  family: Cooper
- given: Sofia
  family: Triantafyllou
- given: Elias
  family: Bareinboim
- given: Huan
  family: Liu
- given: Negar
  family: Kiyavash
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The KDD'21 Workshop on Causal Discovery
    Held in Singapore on 15 August 2021

  Published as Volume 150 by the Proceedings of Machine Learning Research on 02 August 2021.

  Volume Edited by:
    Thuc Duy Le
    Jiuyong Li
    Greg Cooper
    Sofia Triantafyllou
    Elias Bareinboim
    Huan Liu
    Negar Kiyavash

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 15 Aug
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v150"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v150
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v150
email: ''
conference:
  name: The KDD'21 Workshop on Causal Discovery
  url: https://nugget.unisa.edu.au/workshop-program.html
  location: Singapore
  dates:
  - 2021-08-15
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v150/bibliographyCD2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v150/bibliographyCD2021.bib
